### PR TITLE
Update the styling for Restaurant and Dish 

### PR DESCRIPTION
**Pull request by devin-efendy**
Update the styling for Restaurant and Dish

**Screenshot:**

Selecting Restaurant:
Screen Shot 2020-11-13 at 10 37 06 PM

Selecting Dish:
Screen Shot 2020-11-13 at 10 37 24 PM

### CODE REVIEW

**Comment by devin-efendy** [comment]
@quangduy377 @joegodard @raul-gonzales 

Please review this PR. I tried my best to follow our original idea. Let me know if you guys have any suggestion (font, size, color, shadow, anything)

**Comment by devin-efendy** [comment]
About the dish images. That's intentional and I think we can justify them in the writing. e.g., take way too much time to collect the picture

**Comment by raul-gonzales** [comment]
I noticed that the dishes list are in front of the navigation bar when scrolling through them if it is no longer in budget, other than that, it looks great!

**Comment by devin-efendy** [comment]
Which browser are you using? @raul-gonzales

**Comment by raul-gonzales** [comment]
I'm using microsoft edge, and I tried it on chrome just now and same result.

**Comment by devin-efendy** [comment]
Okay. Should be fixed now.

**Review by joegodard — APPROVED** [review]

**Pull request merged**
