### PR TITLE
Created Navigation bar for the application

### PR DESCRIPTION
**Pull request by devin-efendy**
**Changelog:**
- Added navigation bar which includes
  - User state (e.g., selecting restaurant or dish)
  - Address input
  - Wallet input
  - Cart button
  - Back button
- Change the position to be `sticky`
- Created general states for the application
- Renamed `Header.js` to `NavigationBar.js`
- `Wallet` component now is in `NavigationBar.js` (not as a separate component). Since the component is small enough.

Screenshot:
Screen Shot 2020-11-08 at 5 39 11 PM

### CODE REVIEW

**Comment by devin-efendy** [comment]
@quangduy377 @joegodard @raul-gonzales 

Are you guys okay with this navigation bar? if not, let me know and I'll make some changes or add anything that you guys want.

**Comment by joegodard** [comment]
I would just add another box for the wallet part saying how much money is left in the wallet, otherwise it looks good

**Comment by raul-gonzales** [comment]
It looks good to me too

**Comment by devin-efendy** [comment]
Hey, what do you guys think about only having one input?
1. The user will put their budget in that box.
2. Every time they select something we just subtract the value in that box.
3. But we can have a tooltip that when hovered it show their original budget.

I am doing the other input but it feels kind of redundant (?) but not sure.

**Comment by raul-gonzales** [comment]
Personally, I think we should have the " Set budget" and "Remaining budget" values always visible. It might not be intuitive enough for users to "hover" over the box to find out what value they initially set.
It's also less work for users since they just need to look at the navbar (1 step) vs. move mouse to navbar and then look at tooltip (2 steps).

I was thinking we would have a (button + textbox) that sets the budget value when clicked, and then the value is passed onto a textbox below it which would have values subtracted from it when a dish is selected (kinda like the image below).

navbar interface

**P.S.** the image above is an edited version of the navbar using **paint** (I don't have codes for it)

**Comment by joegodard** [comment]
Ya I agree with Raul

**Comment by quangduy377** [comment]
I like it. It looks good. I think the remaining area should not have the
box next to it. Instead, we simply show the money they have left so the
consumers won't get confused in deciding which box to fill in. If you want
to keep consistency between sections, the remaining box should be
unchangeable by users.

**Comment by devin-efendy** [comment]
Screen Shot 2020-11-10 at 2 29 49 PM

Here is the updated version.

I make the remaining section to not be clickable. For the budget input, I'll put some styling on hover. The user will definitely know which one that they can click.

Will merge this in, if anyone doesn't have anything that they want to change.

**Pull request merged**
